import copy
import glob
import itertools
from datetime import datetime
from functools import lru_cache
from pathlib import Path
from typing import Any

import frontmatter
import requests
import yaml

ROOT = Path(__file__).parent.parent
DATA_PATH = ROOT / '_data'
COLLECTIONS_PATH = ROOT / 'content'
LATTES_JCR_PATH = DATA_PATH / 'lattes_jcr.yml'
LATTES_CITATION_PATH = DATA_PATH / 'lattes_citation.yml'
OPENALEX_CITATION_PATH = DATA_PATH / 'openalex_citation.yml'

LATTES_JCR_API = 'https://buscatextual.cnpq.br/buscatextual/visualizacao.do'
LATTES_CITATION_API = 'https://buscatextual.cnpq.br/buscatextual/servletcitacoes'
OPENALEX_WORKS_API = 'https://api.openalex.org/works/'



def update_list_by_dict(target: list, value: dict):
  """
  Updates a list using keys from dictionary
  May be helpful if you want a fuzzy update of a list
  If key greater than list size, list will be extended
  If list value is dict, it's deep updated
  """
  for k, v in value.items():
    idx = int(k)
    if idx >= len(target):
      target.extend(itertools.repeat(None, idx - len(target) + 1))
    if isinstance(target[idx], dict) and isinstance(v, dict):
      deep_update(target[idx], v)
    else:
      target[idx] = v



def deep_update(target: dict, update: dict):
  """Deep update target dict with update
  For each k,v in update: if k doesn't exist in target, it is deep copied from
  update to target.
  Nested lists are extend if you update by the list and updated if you update by dictionary
  """
  for k, v in update.items():
    curr_val = None
    if isinstance(target, dict):
      if k not in target:
        target[k] = copy.deepcopy(v)

      curr_val = target[k]

    if isinstance(curr_val, list):
      if isinstance(v, list):
        curr_val.extend(copy.deepcopy(v))
      elif isinstance(v, dict):
        update_list_by_dict(curr_val, v)
      else:
        curr_val.extend(v)
    elif isinstance(curr_val, dict):
      deep_update(target[k], v)
    elif isinstance(curr_val, set):
      if not k in target:
        target[k] = v.copy()
      else:
        target[k].update(v.copy())
    else:
      target[k] = copy.copy(v)



def get_collection_path(collection: str):
  return COLLECTIONS_PATH / f'_{collection}'


def load_collection_metadata(collection: str):
  paths = get_collection_path(collection).glob('*.md')
  data = []
  
  for path in paths:
    metadata, _ = frontmatter.parse(path.read_text())
    data.append(metadata)
  
  return data


def load_data(collection: str, lower_keys: bool = False, lower_values: bool = False):
  path = [*DATA_PATH.glob(f'{collection}*')][0]
  data = yaml.safe_load(path.read_text())
  if lower_keys:
    data = { k.lower(): v for k, v in data.items() }
  if lower_values:
    data = { k: v.lower() for k, v in data.items() }
  return data


def get_issn_mapping(transform: bool = True):
  venues = load_data('venues', lower_keys=True)
  
  # transform abbreviations in std
  if transform:
    issn = {v['issn']: v.get('name', k) for k, v in venues.items() if v.get('issn')}
  else:
    issn = {v['issn']: k for k, v in venues.items() if v.get('issn')}

  return issn # issn <-> venue_std


def reverse_mapping(mapping: dict):
  return {v: k for k, v in mapping.items()}


def write_yaml(obj: Any, path: Path, merge: bool = True):
  data = {}
  
  if merge and path.exists():
    data = yaml.safe_load(path.read_text())
  
  deep_update(data, obj)
  output = f'# Automatically generated by {Path(__file__).name}\n'
  output += f'# Updated at {datetime.today().strftime('%Y-%m-%d')}\n'
  output += yaml.dump(data, sort_keys=False)
  path.write_text(output)
      

def find_issn_openalex(publications: list[dict], ignore_cache: bool = False):
  pass


def fetch_jcr_lattes():
  issn_venue_mapping = get_issn_mapping(False)
  issn_venue_mapping_std = get_issn_mapping()
  
  reverse_index = {}
  for issn in issn_venue_mapping.keys():
    resp = requests.get(
      LATTES_JCR_API, 
      params={
        'metodo': 'ajax',
        'acao': 'jcr',
        'issn': str(issn).replace('-', '')
      }, 
      headers={
        'user-agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:149.0) Gecko/20100101 Firefox/149.0',
        'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'host': 'buscatextual.cnpq.br',
      }
    )
    
    try:
      data = resp.json()
      jif = float(data['fator-impacto'])
      year = int(data['ano'])
      value = dict(jif=jif, year=year, update_date=datetime.today().strftime('%Y-%m-%d'))
      reverse_index[issn_venue_mapping[issn]] = value
      reverse_index[issn_venue_mapping_std[issn]] = {**value}
    except Exception:
      value = dict(jif=-1, update_date=datetime.today().strftime('%Y-%m-%d'))
      reverse_index[issn_venue_mapping[issn]] = value
      reverse_index[issn_venue_mapping_std[issn]] = {**value}

  write_yaml(reverse_index, LATTES_JCR_PATH)
  


def fetch_citations_lattes():
  publications = load_collection_metadata('publications')
  publications = [p for p in publications if p.get('doi')]
  
  index = {}
  
  for pub in publications:
    resp = requests.get(
      LATTES_CITATION_API,
      params={'doi': pub['doi']},
      headers={
        'user-agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:149.0) Gecko/20100101 Firefox/149.0',
        'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'host': 'buscatextual.cnpq.br',
      },
    )
    
    values = {}
    try:
      data = resp.json()
      for source in data['citacoes']:
        if str(source['base']) == '1':
          values['wos'] = source['qtd']
        elif str(source['base']) == '3':
          values['scopus'] = source['qtd']
    except Exception:
      pass
    
    values['update_date'] = datetime.today().strftime('%Y-%m-%d')
    index[pub['doi']] = values
  
  write_yaml(index, LATTES_CITATION_PATH)
  
  

def fetch_citations_openalex():
  publications = load_collection_metadata('publications')
  publications = [p for p in publications if p.get('doi')]
  
  index = {}
  
  for pub in publications:
    resp = requests.get(
      OPENALEX_WORKS_API + 'doi:' + pub['doi'],
      headers={
        'user-agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:149.0) Gecko/20100101 Firefox/149.0',
        'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'host': 'api.openalex.org',
      },
    )
    
    values = {}
    try:
      data = resp.json()
      if data['cited_by_count'] > 0:
        values['count'] = data['cited_by_count']
    except Exception:
      pass
    
    values['update_date'] = datetime.today().strftime('%Y-%m-%d')
    index[pub['doi']] = values
  
  write_yaml(index, OPENALEX_CITATION_PATH)



def main():
  # fetch_jcr_lattes()
  # fetch_citations_lattes()
  fetch_citations_openalex()



if __name__ == "__main__":
  main()
